#!/usr/bin/env bash

. "$HOME"/.doctype/scripts/to-md

prev()
{
  if [ "$#" -eq 0 ]; then
    # Save temp file
    tmpfile=$(mktemp).html

    # Run Include and format to Markdown
    xmllint --xinclude - |\
      to-xhtml > "$tmpfile"

    # Open with browser
    (firefox "$tmpfile") & disown
  else
    for file in "$@"; do
      # Save temp file
      tmpfile=$(mktemp).html

      # Run Include and format to Markdown
      xmllint --xinclude "$file" |\
        to-xhtml > "$tmpfile"

      # Open with browser
      (firefox "$tmpfile") & disown
    done
  fi
}
