#!/usr/bin/enb bash

# === schemas and dtd === #
META_DTD="$HOME"/.doctype/dtd/document.dtd

# Validates against dtd
valid()
{
  if [ "$#" -eq 0 ]; then
    xmllint --dtdvalid "$META_DTD" --noout - && \
      echo "Document validates."
  else
    for file in "$@"; do
      xmllint --dtdvalid "$META_DTD" "$file" --noout && \
        echo "Document validates."
    done
  fi
}

